apiVersion: v1
kind: Pod
metadata:
  name: debug-nyann
  namespace: nyann-bench
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: quay.io/rh-ee-tosokin/nyann-bench-shell:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
